// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlmI8wu2BTGkCNfmQPpNMqO0c37WxoM9o',
    appId: '1:1071671271912:web:63fa720186ac0482b0845d',
    messagingSenderId: '1071671271912',
    projectId: 'noti-32f45',
    authDomain: 'noti-32f45.firebaseapp.com',
    storageBucket: 'noti-32f45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxkbpUOFlYvxBxKwyz7mnmvQJs0LvZ6ZQ',
    appId: '1:1071671271912:android:e19afdd2cd21ed32b0845d',
    messagingSenderId: '1071671271912',
    projectId: 'noti-32f45',
    storageBucket: 'noti-32f45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq5tLlDyevZ_PLbEPqwxh0Y2lSUiWpQAA',
    appId: '1:1071671271912:ios:a746320ab1f3b827b0845d',
    messagingSenderId: '1071671271912',
    projectId: 'noti-32f45',
    storageBucket: 'noti-32f45.appspot.com',
    iosBundleId: 'com.example.noti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq5tLlDyevZ_PLbEPqwxh0Y2lSUiWpQAA',
    appId: '1:1071671271912:ios:59a2c78ce1818087b0845d',
    messagingSenderId: '1071671271912',
    projectId: 'noti-32f45',
    storageBucket: 'noti-32f45.appspot.com',
    iosBundleId: 'com.example.noti.RunnerTests',
  );
}
